default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :tests do
    run_tests(
	scheme: "TDDBasics",
	derived_data_path: "./Build/",
	code_coverage: true,
	output_types: "junit",
	clean: true
    )
    sh("bash ../xccov-to-sonarqube-generic.sh ../Build/Logs/Test/*.xcresult/ > ../cov.xml")
  end
  lane :generate_code_coverage do
    sh("bash ../xccov-to-sonarqube-generic.sh ../Build/Logs/Test/*.xcresult/ > ../sonarqube-generic-coverage.xml")
  end
end
