name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  fastlane:
    name: Fastlane Generate code coverage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: pwd && ls
#      - run: brew install sonar-scanner
#      - run: export SONAR_TOKEN=45e763437e83b02038ae096efd43f7f8c7857c2f && echo $SONAR_TOKEN
      - run: fastlane tests
#      - run: bash sonarcloud-scan.sh
  sonarcloud:
    needs: fastlane
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: pwd && ls
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.organization=nnininnine
            -Dsonar.projectKey=nnininnine_TDDBasics
            -Dsonar.swift.coverage.reportPaths=cov.xml
            -Dsonar.coverageReportPaths=cov.xml
            -Dsonar.sources=.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
